[glass-easel-backend-config]
name = "sample"
description = "Sample backend configuration."
major-version = 1
minor-version = 0


[[global-attribute]]
name = "tabindex"
description = "The tab-index of the element."


[[global-event]]
name = "tap"
description = "When an element or component is clicked or touched."
reference = "https://example.com/event/tap"

[[global-event]]
name = "canceltap"
reference = "https://example.com/event/canceltap"


[[element]]
tag-name = "div"
description = "The `div` element."
reference = "https://developer.mozilla.org/en-US/docs/Web/HTML/Element/div"

[[element.attribute]]
name = "aria-checked"
reference = "https://example.com/attribute/aria-checked"

[[element.attribute.value-option]]
value = "false"
description = "The element supports being checked but is not currently checked."

[[element.attribute.value-option]]
value = "true"
description = "The element is checked."

[[element.attribute.value-option]]
value = "mixed"
description = "Indicating a mixed mode value of neither checked nor unchecked."

[[element.event]]
name = "click"


[[element]]
tag-name = "anchor"
description = "(deprecated element)"
deprecated = true

[[element.attribute]]
name = "href"
description = "(deprecated attribute)"
deprecated = true


[[component]]
tag-name = "view"
description = "The `view` component."
reference = "https://example.com/view"

[[component.property]]
name = "hidden"
ty = "boolean"
description = "Whether the component should be hidden, a.k.a. `display: none`."
reference = "https://example.com/view/hidden"

[[component.event]]
name = "hoverstart"
description = "When it enters hover state."
reference = "https://example.com/event/view/hoverstart"

[[component.event]]
name = "hoverend"
description = "When it leaves hover state."
reference = "https://example.com/event/view/hoverend"


[[media-type]]
name = "screen"
description = "Intended primarily for screens."
reference = "https://example.com/media-type/screen"

[[media-type]]
name = "print"
description = "Intended for paged material and documents viewed on a screen in print preview mode."


[[media-feature]]
name = "width"
ty = "range"
description = "Width of the page."
reference = "https://example.com/media-feature/width"

[[media-feature]]
name = "prefers-color-scheme"
ty = "any"
options = ["light", "dark"]
description = "The current color scheme."

[[media-feature]]
name = "monochrome"
description = "Intended for monochrome display."


[[pseudo-class]]
name = "hover"
description = "Matches mouse hovers."
reference = "https://example.com/pseudo-class/hover"

[[pseudo-class]]
name = "active"
description = "Matches when activated, a.k.a. clicked."


[[pseudo-element]]
name = "before"
description = "A pseudo-element that is the first child of the selected element."
reference = "https://example.com/pseudo-element/before"

[[pseudo-element]]
name = "after"
description = "A pseudo-element that is the last child of the selected element."


[[style-property]]
name = "color"
description = "The font color."
reference = "https://example.com/property/color"

[[style-property]]
name = "display"
options = ["block", "inline", "inline-block", "flex", "none"]
description = "The display mode."
